// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwztewxmzwdkczmdhdfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3enRld3htendka2N6bWRoZGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDY1NDgsImV4cCI6MjA2NDI4MjU0OH0.C9A9aasTnG-zGihCa0z90zU2gdsMIAJiFi-w00X_syA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);